export const actions = [
	"bonked",
	"wacked",
	"slapped",
	"hit",
	"jumped",
	"smacked",
	"spun",
	"knocked",
	"socked",
	"thwacked",
	"punched",
	"fried",
	"donked",
	"kicked",
	"tapped",
	"struck",
	"bapped",
	"bopped",
	"headbutted",
	"karate chopped",
	"dropkicked",
	"body slammed",
	"booped",
	"lightly smacked",
	"forcefully pushed",
	"sneak attacked",
	"swiftly bonked",
	"gently tapped",
	"dramatically slapped",
	"casually flicked",
	"accidentally tripped",
	"yeeted",
	"bounced off",
	"pelted",
	"catapulted",
	"blasted",
	"power-slammed",
	"reverse bonked",
	"mega-punched",
	"lightly bonked",
	"playfully smacked",
	"comically bumped",
	"swooped down on",
	"sucker-punched",
	"smite'd",
	"slammed",
	"face-palmed",
	"ambushed",
	"snuck up and bonked",
	"surprised"
];

export const objects = [
	"a fish",
	"a frying pan",
	"a bat",
	"a pancake",
	"a toaster",
	"a single fry",
	"a chocolate bar",
	"their bank balance",
	"some glasses",
	"a tomato",
	"an apple",
	"a couch",
	"a bed",
	"an egg",
	"a harmonica",
	"a slice of pizza",
	"a sandwich",
	"a bag of chips",
	"a donut",
	"a cup of coffee",
	"a pie",
	"a cupcake",
	"a burrito",
	"a taco",
	"a giant cookie",
	"a banana peel",
	"a baguette",
	"a marshmallow",
	"a spoonful of cereal",
	"a lemon",
	"a jar of peanut butter",
	"a milkshake",
	"a watermelon",
	"a popsicle",
	"a sandwich of confusion",
	"a plushie",
	"a pillow",
	"a rubber chicken",
	"a traffic cone",
	"a paper airplane",
	"a slinky",
	"a teddy bear",
	"a plastic sword",
	"a pool noodle",
	"a balloon",
	"a snowball",
	"a rubber duck",
	"a nerf dart",
	"a frisbee",
	"a keyboard",
	"a controller",
	"a yo-yo",
	"a magic 8-ball",
	"a broom",
	"a sponge",
	"a plush shark",
	"a beanbag",
	"a kazoo",
	"a paintbrush",
	"a sparkler",
	"a bucket of glitter",
	"a rainbow",
	"a shoe",
	"a laptop charger",
	"a scroll of memes",
	"a USB stick",
	"a cursed artifact",
	"a sock of destiny",
	"a water balloon",
	"a snow shovel",
	"a potted plant",
	"a floppy disk",
	"a random potato",
	"a dictionary",
	"a broken lightbulb",
	"a spoon",
	"a slice of chaos",
	"a bag of mystery",
	"a bundle of energy",
	"a glowing orb",
	"a mystical banana",
	"a plush duck army",
	"a pillow of doom",
	"a rubber mallet",
	"a confetti cannon",
	"a bucket of popcorn",
	"a bouquet of flowers",
	"a rubber hose",
	"a loaf of bread",
	"a cup of tea",
	"a cosmic brick",
	"a mysterious scroll",
	"a bubble wand",
	"a piece of cheese",
	"a rolled-up newspaper",
	"a soggy sponge",
	"a spark of chaos",
	"a stick of butter",
	"a glowing cube",
	"a cursed sandwich",
	"a Blåhaj"
];