export const replies = [
	"Maybe.",
	"Certainly not.",
	"I hope so.",
	"Not in your wildest dreams.",
	"There is a good chance.",
	"Quite likely.",
	"I think so.",
	"I hope not.",
	"Never!",
	"Pfft.",
	"Sorry, bucko.",
	"Hell, yes.",
	"Hell to the no.",
	"The future is bleak.",
	"The future is uncertain.",
	"I would rather not say.",
	"Who cares?",
	"Possibly.",
	"Never, ever, ever.",
	"There is a small chance.",
	"Yes!",
	"lol no.",
	"There is a high probability.",
	"What difference does it make?",
	"Not my problem.",
	"Ask someone else.",
	"Absolutely.",
	"100% yes.",
	"Without a single doubt.",
	"The stars have literally aligned for this.",
	"Bet everything on it.",
	"Signs point to absolutely.",
	"You already know the answer is yes.",
	"Manifesting this for you.",
	"The odds are heavily in your favor.",
	"Looking very good.",
	"My crystal ball says go for it.",
	"Ask again when I care.",
	"Better not tell you now.",
	"Concentrate and try again later.",
	"Reply hazy, try shifting your perspective.",
	"That information is classified.",
	"The vibes are completely unreadable right now.",
	"I'm legally obligated not to answer that.",
	"Loading answer... please wait.",
	"My sources are currently ghosting me.",
	"Bruh, no.",
	"Next question, please.",
	"Why are you asking a bot this?",
	"Error 404: Care not found.",
	"I'm going to pretend I didn't read that.",
	"Does it look like I know?",
	"Googling it would give you a better answer.",
	"Don't shoot the messenger, but no.",
	"Sure, whatever helps you sleep at night.",
	"Figure it out yourself.",
	"Bold of you to assume.",
	"Meh.",
	"Don't count on it.",
	"Outlook is highly questionable.",
	"Highly unlikely.",
	"Don't hold your breath.",
	"The universe is saying 'try again in another lifetime'.",
	"My gut says no, and I don't even have a gut.",
	"You're not going to like the answer.",
	"Hard pass.",
	"Absolutely not.",
	"Not even if you paid me.",
	"It's over.",
	"In your absolute dreams.",
	"A million times no.",
	"The answer is a resounding, echoing no.",
	"Delete this question.",
	"Fat chance.",
	"Not happening.",
	"The simulation says no."
] as const;